### ISSUE TITLE
Auth/R Studio

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform#15]
## What happened?

Hayden tried to log into the platform (R Studio).  He says:

"The default login had changed to my gmail address rather than the usual “sign in with github”. I tried both a couple of times and I typed in the authenticator code fine - managed to get in on about the 5th attempt"

The error message he received was:

```
InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:379:17)
    at /app/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /app/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:162:5)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1025:8)
```

**Comment by xoen** [comment]
It may be an intermitted thing on Auth0 end (I just tried and it worked fine).
I saw few errors on their status page the last few days.

**Comment by kerin** [comment]
This issue is a bit of a mystery, as only Github logins are permitted on RStudio instances - I've just confirmed that RStudio and Auth0 config is still correct, and it is, so closing this for now.
