### ISSUE TITLE
Creating a new data bucket fails silently

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform#81]
## What happened?

I tried to create a new data bucket using Control Panel, but when there was an error (I assume the bucket name was not available) it didn't tell me there was anything wrong - it displayed a different looking form to ask the question again.

Form 1:
![screen shot 2018-11-07 at 17 40 50](https://user-images.githubusercontent.com/307612/48150065-9580bc00-e2b5-11e8-945d-501b1ae5c646.png)

Form 2:
![screen shot 2018-11-07 at 17 41 05](https://user-images.githubusercontent.com/307612/48150081-9c0f3380-e2b5-11e8-9d44-ed51a0b777a5.png)

In addition, let's be clearer about what we call this thing we are creating. It's variously called:
* "Warehouse data source"
* "Warehouse data source (bucket)"
* "secure data storage folder"
* "data source (bucket)"
* "data source"

## Steps to reproduce the problem

1. [On dev, start on Control Panel 'Warehouse data' tab](https://cpanel-master.services.dev.mojanalytics.xyz/#Warehouse%20data)
2. Click "Create new warehouse data source"
3. (Form 1) Call it "dev-test1" (I'm doing this on dev) and click "Create"
4. (Form 2) essentially repeats the question, with no error message.

## Expected behaviour

Display an error message

**Comment by davidread** [comment]
Ah, form 2 creates a WebApp data bucket, not a Warehouse data bucket that we originally asked for! So the error handling is really wrong.

**Comment by davidread** [comment]
In the logs I see problems getting AWS creds:
```
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,023 botocore.session DEBUG Loading variable profile from defaults.
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,024 botocore.session DEBUG Loading variable region from defaults.
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,024 botocore.session DEBUG Loading variable profile from defaults.
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,024 botocore.session DEBUG Loading variable ca_bundle from defaults.
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,024 botocore.session DEBUG Loading variable profile from defaults.
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,024 botocore.session DEBUG Loading variable api_versions from defaults.
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,024 botocore.session DEBUG Loading variable profile from defaults.
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,024 botocore.hooks DEBUG Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f9600168158>
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,026 botocore.hooks DEBUG Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f96001abd08>
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,026 botocore.hooks DEBUG Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f95fdf81e18>
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,026 botocore.hooks DEBUG Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f96001abae8>
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,026 botocore.args DEBUG The s3 config key is not a dictionary type, ignoring its value of: None
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,030 botocore.endpoint DEBUG Setting s3 timeout as (60, 60)
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,030 botocore.client DEBUG Registering retry handlers for service: s3
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,031 botocore.client DEBUG Defaulting to S3 virtual host style addressing with path style addressing fallback.
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,036 botocore.hooks DEBUG Event before-parameter-build.s3.CreateBucket: calling handler <function validate_bucket_name at 0x7f960017a840>
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,036 botocore.hooks DEBUG Event before-parameter-build.s3.CreateBucket: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f95fd264588>>
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,036 botocore.hooks DEBUG Event before-parameter-build.s3.CreateBucket: calling handler <function generate_idempotent_uuid at 0x7f960017a488>
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,037 botocore.hooks DEBUG Event before-call.s3.CreateBucket: calling handler <function add_expect_header at 0x7f960017ad08>
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,037 botocore.hooks DEBUG Event before-call.s3.CreateBucket: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7f95fd264588>>
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,037 botocore.endpoint DEBUG Making request for OperationModel(name=CreateBucket) (verify_ssl=True) with params: {'url_path': '/alpha-prison-population-hub', 'query_string': {}, 'method': 'PUT', 'headers': {'x-amz-acl': 'private', 'User-Agent': 'Boto3/1.7.77 Python/3.6.5 Linux/4.4.121-k8s Botocore/1.10.77'}, 'body': b'<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LocationConstraint>eu-west-1</LocationConstraint></CreateBucketConfiguration>', 'url': 'https://s3.amazonaws.com/alpha-prison-population-hub', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x7f95fd4e2d30>, 'has_streaming_input': False, 'auth_type': None, 'signing': {'bucket': 'alpha-prison-population-hub'}}}
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,037 botocore.hooks DEBUG Event request-created.s3.CreateBucket: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f95fd4e2fd0>>
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,038 botocore.hooks DEBUG Event choose-signer.s3.CreateBucket: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x7f95fd9d14e0>>
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,038 botocore.hooks DEBUG Event choose-signer.s3.CreateBucket: calling handler <function set_operation_specific_signer at 0x7f960017a378>
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,038 botocore.hooks DEBUG Event before-sign.s3.CreateBucket: calling handler <function fix_s3_host at 0x7f96002b3400>
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,038 botocore.utils DEBUG Checking for DNS compatible bucket for: https://s3.amazonaws.com/alpha-prison-population-hub
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,038 botocore.utils DEBUG URI updated to: https://alpha-prison-population-hub.s3.amazonaws.com/
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,039 botocore.credentials DEBUG Credentials need to be refreshed.
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,039 botocore.credentials DEBUG Credentials need to be refreshed.
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,039 botocore.credentials DEBUG Credentials need to be refreshed.
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,049 botocore.vendored.requests.packages.urllib3.connectionpool INFO Starting new HTTP connection (1): 169.254.169.254
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,050 botocore.utils DEBUG Caught exception while trying to retrieve credentials: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
cpanel-master-cpanel-5f57886f84-p9fz8 api Traceback (most recent call last):
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
cpanel-master-cpanel-5f57886f84-p9fz8 api     body=body, headers=headers)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
cpanel-master-cpanel-5f57886f84-p9fz8 api     conn.request(method, url, **httplib_request_kw)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/http/client.py", line 1239, in request
cpanel-master-cpanel-5f57886f84-p9fz8 api     self._send_request(method, url, body, headers, encode_chunked)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/awsrequest.py", line 130, in _send_request
cpanel-master-cpanel-5f57886f84-p9fz8 api     self, method, url, body, headers, *args, **kwargs)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
cpanel-master-cpanel-5f57886f84-p9fz8 api     self.endheaders(body, encode_chunked=encode_chunked)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
cpanel-master-cpanel-5f57886f84-p9fz8 api     self._send_output(message_body, encode_chunked=encode_chunked)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/awsrequest.py", line 157, in _send_output
cpanel-master-cpanel-5f57886f84-p9fz8 api     self.send(msg)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/awsrequest.py", line 242, in send
cpanel-master-cpanel-5f57886f84-p9fz8 api     return HTTPConnection.send(self, str)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/http/client.py", line 964, in send
cpanel-master-cpanel-5f57886f84-p9fz8 api     self.connect()
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 155, in connect
cpanel-master-cpanel-5f57886f84-p9fz8 api     conn = self._new_conn()
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 134, in _new_conn
cpanel-master-cpanel-5f57886f84-p9fz8 api     (self.host, self.port), self.timeout, **extra_kw)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 88, in create_connection
cpanel-master-cpanel-5f57886f84-p9fz8 api     raise err
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 78, in create_connection
cpanel-master-cpanel-5f57886f84-p9fz8 api     sock.connect(sa)
cpanel-master-cpanel-5f57886f84-p9fz8 api ConnectionRefusedError: [Errno 111] Connection refused
cpanel-master-cpanel-5f57886f84-p9fz8 api
cpanel-master-cpanel-5f57886f84-p9fz8 api During handling of the above exception, another exception occurred:
cpanel-master-cpanel-5f57886f84-p9fz8 api
cpanel-master-cpanel-5f57886f84-p9fz8 api Traceback (most recent call last):
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
cpanel-master-cpanel-5f57886f84-p9fz8 api     timeout=timeout
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
cpanel-master-cpanel-5f57886f84-p9fz8 api     _stacktrace=sys.exc_info()[2])
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/util/retry.py", line 245, in increment
cpanel-master-cpanel-5f57886f84-p9fz8 api     raise six.reraise(type(error), error, _stacktrace)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/packages/six.py", line 309, in reraise
cpanel-master-cpanel-5f57886f84-p9fz8 api     raise value.with_traceback(tb)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
cpanel-master-cpanel-5f57886f84-p9fz8 api     body=body, headers=headers)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
cpanel-master-cpanel-5f57886f84-p9fz8 api     conn.request(method, url, **httplib_request_kw)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/http/client.py", line 1239, in request
cpanel-master-cpanel-5f57886f84-p9fz8 api     self._send_request(method, url, body, headers, encode_chunked)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/awsrequest.py", line 130, in _send_request
cpanel-master-cpanel-5f57886f84-p9fz8 api     self, method, url, body, headers, *args, **kwargs)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
cpanel-master-cpanel-5f57886f84-p9fz8 api     self.endheaders(body, encode_chunked=encode_chunked)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
cpanel-master-cpanel-5f57886f84-p9fz8 api     self._send_output(message_body, encode_chunked=encode_chunked)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/awsrequest.py", line 157, in _send_output
cpanel-master-cpanel-5f57886f84-p9fz8 api     self.send(msg)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/awsrequest.py", line 242, in send
cpanel-master-cpanel-5f57886f84-p9fz8 api     return HTTPConnection.send(self, str)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/http/client.py", line 964, in send
cpanel-master-cpanel-5f57886f84-p9fz8 api     self.connect()
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 155, in connect
cpanel-master-cpanel-5f57886f84-p9fz8 api     conn = self._new_conn()
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 134, in _new_conn
cpanel-master-cpanel-5f57886f84-p9fz8 api     (self.host, self.port), self.timeout, **extra_kw)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 88, in create_connection
cpanel-master-cpanel-5f57886f84-p9fz8 api     raise err
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/util/connection.py", line 78, in create_connection
cpanel-master-cpanel-5f57886f84-p9fz8 api     sock.connect(sa)
cpanel-master-cpanel-5f57886f84-p9fz8 api botocore.vendored.requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
cpanel-master-cpanel-5f57886f84-p9fz8 api
cpanel-master-cpanel-5f57886f84-p9fz8 api During handling of the above exception, another exception occurred:
cpanel-master-cpanel-5f57886f84-p9fz8 api
cpanel-master-cpanel-5f57886f84-p9fz8 api Traceback (most recent call last):
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/utils.py", line 185, in _get_request
cpanel-master-cpanel-5f57886f84-p9fz8 api     response = requests.get(url, timeout=timeout, headers=headers)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/api.py", line 69, in get
cpanel-master-cpanel-5f57886f84-p9fz8 api     return request('get', url, params=params, **kwargs)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/api.py", line 50, in request
cpanel-master-cpanel-5f57886f84-p9fz8 api     response = session.request(method=method, url=url, **kwargs)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 465, in request
cpanel-master-cpanel-5f57886f84-p9fz8 api     resp = self.send(prep, **send_kwargs)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
cpanel-master-cpanel-5f57886f84-p9fz8 api     r = adapter.send(request, **kwargs)
cpanel-master-cpanel-5f57886f84-p9fz8 api   File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/adapters.py", line 415, in send
cpanel-master-cpanel-5f57886f84-p9fz8 api     raise ConnectionError(err, request=request)
cpanel-master-cpanel-5f57886f84-p9fz8 api botocore.vendored.requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
cpanel-master-cpanel-5f57886f84-p9fz8 api 2018-11-22 14:37:01,051 botocore.utils DEBUG Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
```
